### PR TITLE
Add introduction to transaction traces.

### PR DESCRIPTION
**Pull request by peilun-conflux**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54)

### CODE REVIEW

**Review by sparkmiw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @boqiu, @GeekBerry, @Pana, and @peilun-conflux)

___
*[docs/trace_introduction.md, line 3 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MW9HV8r9cSUfbrQHme-:-MW9HV8r9cSUfbrQHme0:b-tuk5z) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L3)):*
> ```Markdown
> # Introduction to Transaction Traces
> 
> Traces are used to record the transaction execution details. It can be used to debug or retrieving more information (like getting contract addresses created within transaction execution).
> ```

retrieving -> retrieve
___
*[docs/trace_introduction.md, line 43 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MW9IHwE11C9vo5PkMkB:-MW9IHwE11C9vo5PkMkC:bt7i71f) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L43)):*
> ```
> Note that `gas` is the "provided" gas for this `Call` operation
> ```
you mean for the execution of the callee, right?

**Review by sparkmiw — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54)* status: all files reviewed, 2 unresolved discussions (waiting on @boqiu, @GeekBerry, @Pana, and @peilun-conflux)

**Review by boqiu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54)* status: all files reviewed, 3 unresolved discussions (waiting on @GeekBerry, @Pana, and @peilun-conflux)

___
*[docs/trace_introduction.md, line 9 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MWMuLV62qIPVWycwHaJ:-MWMuLV62qIPVWycwHaK:b-qmch36) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L9)):*
> ```Markdown
> ### Call
> 
> The trace is recorded for all `Call` operations, including balance transferring or contract calling.
> ```

Besides the balance transferring or contract call **inside** the contract, how about the transaction itself? Will it always be the first trace for a transaction?

**Review by peilun-conflux — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @boqiu, @GeekBerry, @Pana, and @sparkmiw)

___
*[docs/trace_introduction.md, line 3 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MW9HV8r9cSUfbrQHme-:-MWNPCuYEFdwl40MN_be:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L3)):*
<details><summary><i>Previously, sparkmiw wrote…</i></summary><blockquote>

retrieving -> retrieve
</blockquote></details>

Done.
___
*[docs/trace_introduction.md, line 9 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MWMuLV62qIPVWycwHaJ:-MWNPDQk8KXmEOLdiwis:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L9)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Besides the balance transferring or contract call **inside** the contract, how about the transaction itself? Will it always be the first trace for a transaction?
</blockquote></details>

Done.
___
*[docs/trace_introduction.md, line 43 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-MW9IHwE11C9vo5PkMkB:-MWNPE4wEPLPZChCW3u4:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/4d17d5b7fa65dd3626adf06adf7e3d1063259e73/docs/trace_introduction.md#L43)):*
<details><summary><i>Previously, sparkmiw wrote…</i></summary><blockquote>

> ```
> Note that `gas` is the "provided" gas for this `Call` operation
> ```
you mean for the execution of the callee, right?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-:-MWNtmsA8SGRz3FRbcB_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @GeekBerry, @Pana, and @sparkmiw)

**Review by sparkmiw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/54#-:-MWPU-OFCBO_6jqvuR58:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GeekBerry and @Pana)

**Pull request merged**
