### PR TITLE
Add missing jsonrpc docs

### PR DESCRIPTION
**Pull request by Pana**
There are several rpc not in the current doc

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/36)

### CODE REVIEW

**Comment by Pana** [comment]
@yangzhe1990 Can you review this PR ?

**Review by Thegaram — CHANGES_REQUESTED** [review]
Thank you for adding these. I added a few suggestions and clarifications.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-:-MIPO8J73cnZFF1wdhNJ:b-muhy1u)* status: all files reviewed, 15 unresolved discussions (waiting on @Pana)

___
*[docs/json-rpc.md, line 987 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPFFnr4IY4-BWmyp6u:-MIPFFnr4IY4-BWmyp6v:b-kfd7z9) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L987)):*
> ```
> Check if user balance is enough for the transaction.
> ```

I'd prefer adding a more detailed explanation, e.g.

*Check if a user's balance is enough to send a transaction with the specified gas and storage limits to the specified contract. The balance is enough if the user can cover the up-front payment of both execution and storage, or if these costs are sponsored by the contract.*
___
*[docs/json-rpc.md, line 995 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPHz3d1Ab2RvpgXSoT:-MIPHz3d1Ab2RvpgXSoU:b-uzmvkc) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L995)):*
> ```
> epoch number
> ```

Convention:

*`QUANTITY|TAG` - (optional, default: `"latest_state"`) integer epoch number, or the string `"latest_state"`, `"latest_checkpoint"` or `"earliest"`, see the epoch number parameter [link].*
___
*[docs/json-rpc.md, line 1009 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPGzsB0kHiOIUHmUdn:-MIPGzsB0kHiOIUHmUdo:b-6ll9c3) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1009)):*
> ```
> BOOL
> ```

The convention is `Boolean`.
___
*[docs/json-rpc.md, line 1010 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPH9mCCC-AR4qisaOz:-MIPH9mCCC-AR4qisaP-:b5blx7b) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1010)):*
> ```
> indicate balance is enough for collateral
> ```

This is incorrect. I suggest:

*false if the transaction is eligible for storage collateral sponsorship, true otherwise.*
___
*[docs/json-rpc.md, line 1011 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPHaVQ2Fhb1FCD7P6r:-MIPHaVQ2Fhb1FCD7P6s:b-tr6dz0) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1011)):*
> ```
> `willPayTxFee`: `BOOL` - indicate balance is enough for tx fee
> ```

This is incorrect. I suggest:

*false if the transaction is eligible for gas sponsorship, true otherwise.*
___
*[docs/json-rpc.md, line 1031 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPJuEQ5JdD4sz_b9bM:-MIPJuER0_Yd_b0QjjEp:b-5mjjhq) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1031)):*
> ```
> hashs
> ```

hashes

Maybe add some context?

*Return the list of non-executed blocks in an epoch. By default, Conflux only executes the last 200 blocks in each epoch (note that under normal circumstances, epochs should be much smaller).*
___
*[docs/json-rpc.md, line 1042 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPK5zW37rzspIECVih:-MIPK5zW37rzspIECVii:bislsjk) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1042)):*
> ```
> hashs
> ```
hashes
___
*[docs/json-rpc.md, line 1061 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPLOWGAYY1QZR_xvhM:-MIPLOWGAYY1QZR_xvhN:b-p8pxd8) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1061)):*
> ```
> `DATA`, The block hash.
> ```

`DATA`, 32 Bytes - The block hash.
___
*[docs/json-rpc.md, line 1070 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPLrje1iPzzAQk4-TE:-MIPLrje1iPzzAQk4-TF:bfcpxn9) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1070)):*
> ```
> The confirmation risk number
> ```

The confirmation risk number or `null`.
___
*[docs/json-rpc.md, line 1079 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPMIJ29JavgOtm6EWA:-MIPMIJ29JavgOtm6EWB:bhtj27a) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1079)):*
> ```
> 0x2af31dc4611873bf3f70834acdae9f0f4f534f5d60585a5f1c1a3ced1b
> ```

Would be nice to add some context about how to interpret this... @resodo?
___
*[docs/json-rpc.md, line 1085 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPMPYZ4PMLEPHWyCkc:-MIPMPYZ4PMLEPHWyCkd:b-d5dtrf) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1085)):*
> ```
> Return network status
> ```

*Return node status*
___
*[docs/json-rpc.md, line 1132 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPN6GX40nlBpJsXZS5:-MIPN6GX40nlBpJsXZS6:b-321ki6) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1132)):*
> ```
> conflux-rust-1.0.0
> ```

Maybe it's better to add `conflux-rust-0.6.3` to avoid confusion.
___
*[docs/json-rpc.md, line 1153 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPNN1b6CUigUFKxU19:-MIPNN1b6CUigUFKxU1A:bgy9iuc) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1153)):*
> ```
> include
> ```
including
___
*[docs/json-rpc.md, line 1180 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPNgh22XHdoThM3SpJ:-MIPNgh22XHdoThM3SpK:bj9fa29) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1180)):*
> ```
> Returns block with given hash and pivot chain assumption.
> ```

*Returns the requested block if the provided pivot hash is correct, returns an error otherwise.*
___
*[docs/json-rpc.md, line 1184 at r1](https://reviewable.io/reviews/conflux-chain/conflux-doc/36#-MIPNas56K8TKeED0l86:-MIPNas56K8TKeED0l87:b7ga4co) ([raw file](https://github.com/conflux-chain/conflux-doc/blob/af7796b5ba08a15beab3641ec3b126b061afc6b3/docs/json-rpc.md#L1184)):*
> ```
> QUANTITY`, epoch number
> ```

See above.

**Comment by Pana** [comment]
Thanks @Thegaram for reviewing this

**Review by Thegaram — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/36)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
