### PR TITLE
docs: add zh_cn version of docs on developer.conflux-chain.org

### PR DESCRIPTION
**Pull request by yqrashawn**
docs are from https://github.com/xiaozhu001/conflux-docs/tree/021a753c70abad558d5d41e8e80d32c5d37d285e
contributed by community members

corresponding bounty is
https://bounty.conflux-chain.org/view-bounty?bountyId=5ee32e396f728d65214e735e

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-doc/21)

### CODE REVIEW

**Comment by Thegaram** [comment]
How can we make sure the two versions are in sync?

**Comment by resodo** [comment]
> How can we make sure the two versions are in sync?

Good question, any ideas about the version control of docs? @yqrashawn @angelia-yuqi-personal

**Comment by yqrashawn** [comment]
@Thegaram We can't. 
I discussed it with @royshang. The idea is that we can open another bounty to update the zh_cn docs if there are major changes in en doc.

Two possible solutions:
1. add a notice to each none en doc like "this version might be out of sync with the en version"
2. put all community maintained docs in a separate repo

**Review by AngeliaQ — APPROVED** [review]

**Comment by AngeliaQ** [comment]
> How can we make sure the two versions are in sync?

We can only sync case by case. When the English doc changes, we can mark it and open a bounty to sort out these changes and someone can take the translate task

**Comment by AngeliaQ** [comment]
> > How can we make sure the two versions are in sync?
> 
> Good question, any ideas about the version control of docs? @yqrashawn @angelia-yuqi-personal

I think we can collect changes of en doc at intervals, such as each quarter, and open a bounty to make someone help us to sync the two versions discussing with @royshang

**Comment by yqrashawn** [comment]
@angelia-yuqi-personal and I discussed this offline yesterday. Since we rely on the community to maintain the translations, we better put each trans into a single repo for better maintainability.

**Pull request closed without merging**
